### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by Squidmobile** [crashb/jestercap#18]
Out of date for 1.28

**Comment by Squidmobile** [comment]
I submitted a pull request with updated offsets for 1.28

**Comment by crashb** [comment]
Hi. Thanks very much, I have tested your changes and created a [new release](https://github.com/crashb/jestercap/releases/tag/1.28_01) that includes them. JesterCap is now compatible with version 1.28 of Spelunky 2. Thank you!
