### ISSUE TITLE
Please update JesterCap for the new update

### ISSUE THREAD

**Issue by syncerpn** [crashb/jestercap#6]
Hi @crashb,

I really love your jestercap.
A new patch to spelunky (1.20.1c) was released last few days, so could you please update jestercap?
Thank you!

**Comment by crashb** [comment]
Thank you for the heads-up. I hadn't noticed this update.

**Comment by crashb** [comment]
I've poked around in the disassembly and it looks like this update changed a lot. I will probably get around to updating within the next few days.

Thanks for your patience, I'm happy you are finding it useful <3

**Comment by syncerpn** [comment]
It is really useful <3
If you have time, please make a tutorial as well :D. I would love to learn how you obtain those offsets :D

**Comment by crashb** [comment]
Hi @syncerpn. I've updated the offsets and published a [new release](https://github.com/crashb/jestercap/releases/tag/1.20.1d_01) for yesterday's 1.20.1d update.

Good luck with your True Crown runs!

**Comment by syncerpn** [comment]
Thank you.
It works perfectly :D
