### ISSUE TITLE
1.20.3a_01 not working

### ISSUE THREAD

**Issue by Squidmobile** [crashb/jestercap#7]
The process attaches and it gets the correct score count, but it doesn't notice when the crown is picked up.
![brokencapgithub](https://user-images.githubusercontent.com/53955349/109262173-46c8fa00-77be-11eb-9b6c-1b4dd8d8b9ba.png)

(the hex of Spel2.exe got moved around a bit this update, I assume that's the cause)

**Comment by nith822** [comment]
True Crown Id was changed to 536 from 552

One or more of the offsets below have changed:

private const int OFFSET_NUM_ITEMS = 0X77E;        // the number of items picked up
private const int OFFSET_FIRST_ITEM_ID = 0x784;    // the first item ID in memory
private const int SIZE_ITEM_STRUCT = 0x14;         // the space between each item ID

**Comment by crashb** [comment]
Hi all,

Thanks for letting me know about this problem. Of course, the one time I'm confident enough to release without going through the hoops of getting the crown to test it is the time it breaks... ;)

I'll be able to have a look within the next few days, but in the meantime anyone else is welcome to submit a PR for reviewal.

**Comment by crashb** [comment]
Scratch that, I just released another version. Please give it a try and let me know whether it works for you.

**Comment by nith822** [comment]
It's working. Thanks for the fix

**Comment by crashb** [comment]
Awesome, glad to hear it! Good luck on your True Crown runs :)
