### ISSUE TITLE
doesnt attach correctly

### ISSUE THREAD

**Issue by killhome99** [crashb/jestercap#8]
recently jestercap has been failing the attach, showing points as 56905 and not changing, and one time a negative score of about -3000, anyone else having issues and/or know how to fix it.

**Comment by crashb** [comment]
Hi, I just released another version of JesterCap. Please let me know whether it works for you.

**Comment by killhome99** [comment]
ok sure

**Comment by killhome99** [comment]
so its attached, and updating score correctly, if im lucky and good enough ill try to get a crown

**Comment by crashb** [comment]
I suspect this is fixed as per #7 . Please feel free to let me know if you run into any further problems.
